baseURL: https://www.danielecook.com
footnoteReturnLinkContents: ↩
params:
  AuthorName: Daniel E. Cook
permalinks:
  posts: /:title/
languageCode: "en-us"
title: "Daniel E. Cook"
theme: "theme_dan"
pygmentsCodeFences: true
staticDir: ["static"]

languageCode: "en-us"
copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

author:
  name: "Daniel Cook"

Paginate: 1000

outputs:
  home:
  - HTML
  - RSS
  page:
  - HTML
  - RSS

outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed/index"

taxonomies:
  tags: tags

menu:
  main:
    - identifier: "about"
      name: "about"
      url: "/about/"
      weight: -100
    - identifier: "main"
      name: "blog"
      url: "/"
      weight: -100
    - name: "projects"
      url: "/projects/"
      weight: -99
    - name: "photos"
      url: "/photos/"
      weight: -100
    - identifier: "about"
      name: "about"
      url: "/about/"
      weight: -100
    - identifier: "contact"
      name: "contact"
      url: "/contact/"
      weight: 100